---
- name: Bootstrap DevOps Home Lab (Production Grade & RAM Optimized)
  hosts: all
  become: yes
  vars:
    common_packages:
      - git
      - curl
      - wget
      - vim
      - htop
      - net-tools
      - unzip
      - tar

  tasks:
    # ====================================================
    # 1. HỆ THỐNG & KHO TẢI (SYSTEM PREPARATION)
    # ====================================================
    # LƯU Ý: SWAP VẪN ĐANG BẬT ĐỂ TRÁNH CRASH (OOM)

    # --- KHỐI XỬ LÝ CHO ROCKY LINUX (REDHAT) ---
    - name: Setup for Rocky Linux
      block:
        - name: Install EPEL Release (Rocky)
          dnf:
            name: epel-release
            state: present
        
        # Dùng shell thay vì module dnf để tiết kiệm RAM.
        # Đã xóa tham số 'warn' gây lỗi.
        - name: Update System Packages (Rocky) via Shell
          shell: "dnf update -y"
      when: ansible_facts['os_family'] == "RedHat"

    # --- KHỐI XỬ LÝ CHO UBUNTU (DEBIAN) ---
    - name: Setup for Ubuntu
      block:
        - name: Update System Cache (Ubuntu)
          apt:
            update_cache: yes
            cache_valid_time: 3600
        
        - name: Install Dependencies for Docker Repo (Ubuntu)
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
            state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Common Utilities
      package:
        name: "{{ common_packages }}"
        state: present

    # ====================================================
    # 2. CÀI DOCKER & PYTHON SDK
    # ====================================================
    
    # --- ROCKY LINUX ---
    - name: Docker Installation (Rocky Linux)
      block:
        - name: Add Docker Repo
          get_url:
            url: https://download.docker.com/linux/centos/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo

        - name: Install Docker & Python SDK (Rocky)
          dnf:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
              - python3-pip
            state: present

        - name: Install Python SDK via Pip (Fallback)
          pip:
            name: docker
            executable: pip3
          ignore_errors: yes 
      when: ansible_facts['os_family'] == "RedHat"

    # --- UBUNTU ---
    - name: Docker Installation (Ubuntu)
      block:
        - name: Create keyrings directory
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Add Docker GPG Key
          shell: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
          args:
            creates: /etc/apt/keyrings/docker.gpg

        - name: Add Docker Repository
          shell: |
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          args:
            creates: /etc/apt/sources.list.d/docker.list

        - name: Update Apt Cache
          apt:
            update_cache: yes

        - name: Install Docker & SDK (Ubuntu)
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
              - python3-docker
              - python3-requests
            state: present
      when: ansible_facts['os_family'] == "Debian"

    # ====================================================
    # 3. CẤU HÌNH DỊCH VỤ & BẢO MẬT
    # ====================================================
    - name: Start and Enable Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add 'vagrant' user to 'docker' group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Set permissions on Docker socket
      file:
        path: /var/run/docker.sock
        mode: '0666'

    # --- FIREWALL ---
    - name: Configure Firewalld (Rocky)
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop: [http, https]
      when: ansible_facts['os_family'] == "RedHat"
      ignore_errors: yes

    - name: Configure UFW (Ubuntu)
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: [80, 443]
      when: ansible_facts['os_family'] == "Debian"
      ignore_errors: yes

    # ====================================================
    # 4. CLEANUP (CHẠY CUỐI CÙNG)
    # ====================================================
    - name: Disable Swap (Final Step - Only when everything is ready)
      command: swapoff -a
      when: ansible_facts['swaptotal_mb'] > 0
