---
- name: Setup Web Servers
  hosts: web_servers
  become: yes  # Chạy với quyền sudo
  tasks:
    - name: Install Nginx on Rocky Linux
      dnf:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Allow HTTP/HTTPS through Firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      ignore_errors: yes # Đề phòng máy ảo chưa có python-firewall lib
    - name: Create a custom index.html
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <h1>Hello from {{ ansible_facts['hostname'] }}</h1>
          <p>IP Address: {{ ansible_facts['default_ipv4']['address'] }}</p>
